/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectooptimizacion;

import java.awt.Dimension;
import java.awt.GridLayout;

/**
 *
 * @author HP
 */
public class PanelDatos extends javax.swing.JPanel {

    /**
     * Creates new form PanelDatos
     */
    
    //Variables 
    public static int n,m;
    
    public static double c[], a[][];
    public static int [] r;
    public static int fo;
    public static funcionObjetivo FO;
    
    
    public PanelDatos() {
        initComponents();
        boolean regreso = true;
        
        if(c == null && a == null && r == null ){
            c = new double[n];
            a = new double[m][n+1];
            r = new int [m];
            regreso = false;
            jComboBox1.setSelectedIndex(0);
            
            
        }
        
        if(atras){
            c = new double[n];
            a = new double[m][n+1];
            r = new int [m];
            regreso = false;
            jComboBox1.setSelectedIndex(fo-1);
            
            atras =false;
        }
            
        
        
        
        
        
        entrada =  new javax.swing.JTextField[m][n];
        xs = new javax.swing.JLabel[n];
        fxs = new javax.swing.JLabel[n];
        bi = new javax.swing.JTextField[m];
        fi = new javax.swing.JTextField[n];
        rest = new javax.swing.JComboBox[m];
        panelDatos.setLayout(new GridLayout(m,n,5,5));
        panelFuncion.setLayout(new GridLayout(1,n,10,10));
        
        for (int i = 0; i < m; i++) {
            for (int j = 0; j < n; j++) {
                xs[j] = new javax.swing.JLabel();
                entrada[i][j] = new javax.swing.JTextField();
                if(regreso){
                    entrada[i][j].setText(String.valueOf(a[i][j]));
                }
                if(j==0){
                    xs[j].setText("X" + (j+1) + "+");
                }else{
                    if(j != (n-1)){
                        xs[j].setText("X" + (j+1) + "+");
                    }else{
                        xs[j].setText("X" + (j+1));
                    }
                    
                }
                
                entrada[i][j].setPreferredSize(new Dimension(20, 20));
                
                panelDatos.add(entrada[i][j]);
                panelDatos.add(xs[j]); //
                
                if(i == 0){
                    fxs[j] = new javax.swing.JLabel();
                    fi[j] = new javax.swing.JTextField();
                    fi[j].setPreferredSize(new Dimension(80, 30));
                    if(regreso){
                    fi[j].setText(String.valueOf(c[i]));
                    }
                    if(j==0){
                        fxs[j].setText("X" + (j+1) + "+");
                    }else{
                        if(j == (n-1)){
                            fxs[j].setText("X" + (j+1));
                        }else{
                            fxs[j].setText("X" + (j+1) + "+");
                        }
                        
                    }
                    panelFuncion.add(fi[j]);
                    panelFuncion.add(fxs[j]);
                }
                
            }
            rest[i] = new javax.swing.JComboBox<>();
            
            
            bi[i] = new javax.swing.JTextField();
            if(regreso){
                bi[i].setText(String.valueOf(a[i][n]));
            }
            
            
            bi[i].setPreferredSize(new Dimension(30, 30));
            
            rest[i].setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<=","=",">=" }));
            if(regreso){
                rest[i].setSelectedIndex(r[i] - 1);
            }
            panelDatos.add(rest[i]);
            panelDatos.add(bi[i]);
            
        }
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatos = new javax.swing.JPanel();
        panelFuncion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1000, 720));
        setMinimumSize(new java.awt.Dimension(1000, 720));
        setPreferredSize(new java.awt.Dimension(1000, 720));

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelFuncionLayout = new javax.swing.GroupLayout(panelFuncion);
        panelFuncion.setLayout(panelFuncionLayout);
        panelFuncionLayout.setHorizontalGroup(
            panelFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        panelFuncionLayout.setVerticalGroup(
            panelFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jLabel2.setText("Xi>=0");

        jLabel3.setText("Restricciones");

        jLabel4.setText("FUNCION:");

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel1.setText("¿Cuál es el objetivo de la función?");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MAXIMIZAR", "MINIMIZAR" }));

        jLabel5.setText("METODO SIMPLEX REVISADO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel5)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 295, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(223, 223, 223))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(240, 240, 240))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnIniciar)
                        .addGap(343, 343, 343))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFuncion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras)
                    .addComponent(btnIniciar))
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    public static boolean atras;
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:

        FramePrincipal.PanelPrincipal.remove(FramePrincipal.PD);
        FramePrincipal.PA.setVisible(true);
        FramePrincipal.PD.setVisible(false);
        atras = true;
        MetodoSimplexRevisado.salidaFinal.clear();
    }//GEN-LAST:event_btnAtrasActionPerformed

    
    
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        
        
        
        
        fo = jComboBox1.getSelectedIndex() + 1;

        
        for(int i = 0; i<n;i++){
            if(fi[i].getText().isEmpty()){
                c[i] = 0.0;
            }else{
                c[i] = Double.parseDouble(fi[i].getText());
            }
        }
        
        for(int i = 0;i<m;i++){
            r[i] = rest[i].getSelectedIndex() + 1;
            for(int j = 0; j<n+1;j++){
                
                if(j ==  n){
                    a[i][j] = Double.parseDouble(bi[i].getText());
                }
                
                if(j != n){
                    if(entrada[i][j].getText().isEmpty()){
                        a[i][j] = 0.0;
                    }else{
                        a[i][j] = Double.parseDouble(entrada[i][j].getText());
                    }
                }
                
            }
        }
        FO = new funcionObjetivo();
        FramePrincipal.PanelPrincipal.add(FO);
        FO.setBounds(0, 0, 1000, 720);
        FramePrincipal.PA.setVisible(false);
        FramePrincipal.PD.setVisible(false);
        FO.setVisible(true);
        
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelFuncion;
    // End of variables declaration//GEN-END:variables
    //Para la entrada de datos
    public javax.swing.JTextField[][] entrada; //campo de datos
    public javax.swing.JLabel[] xs; //marca de las Xis
    public javax.swing.JLabel[] fxs; //marca de las Xis
    public javax.swing.JTextField[] bi;//bis
    public javax.swing.JTextField[] fi;//funcion
    public javax.swing.JComboBox<String>[] rest; //valor de restricciones
    

}
