package proyectooptimizacion;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class Resultados extends javax.swing.JPanel {

    /**
     * Creates new form Resultados
     */
    public int bandera = 0;
    public Resultados() {
        initComponents();
        if(!funcionObjetivo.directo){
            datosSalida.setText(MetodoSimplexRevisado.salidaFinal.get(bandera));
        }else{
            datosSalida.setText(MetodoSimplexRevisado.salidaFinal.get(MetodoSimplexRevisado.salidaFinal.size() - 1));
            btnContinuar.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datosSalida = new javax.swing.JTextArea();
        btnAtras = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1000, 720));
        setMinimumSize(new java.awt.Dimension(1000, 720));

        jLabel1.setText("Iteracion : ");

        datosSalida.setColumns(20);
        datosSalida.setRows(5);
        jScrollPane1.setViewportView(datosSalida);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(btnAtras)
                        .addGap(58, 58, 58)
                        .addComponent(btnContinuar)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras)
                    .addComponent(btnContinuar))
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        if(!funcionObjetivo.directo){
            bandera--;
            if(bandera == -1){
                PanelDatos.FO = new funcionObjetivo();
                FramePrincipal.PanelPrincipal.add(PanelDatos.FO);
                PanelDatos.FO.setBounds(0, 0, 1000, 720);
                FramePrincipal.PA.setVisible(false);
                FramePrincipal.PD.setVisible(false);
                funcionObjetivo.RE.setVisible(false);
                PanelDatos.FO.setVisible(true);
                return;
            }

                if(bandera != MetodoSimplexRevisado.salidaFinal.size()){
                    btnContinuar.setEnabled(true);
                    datosSalida.setText(MetodoSimplexRevisado.salidaFinal.get(bandera));

            }
        }else{
                PanelDatos.FO = new funcionObjetivo();
                FramePrincipal.PanelPrincipal.add(PanelDatos.FO);
                PanelDatos.FO.setBounds(0, 0, 1000, 720);
                FramePrincipal.PA.setVisible(false);
                FramePrincipal.PD.setVisible(false);
                funcionObjetivo.RE.setVisible(false);
                PanelDatos.FO.setVisible(true); 
                funcionObjetivo.directo =false;
                
        }
        
        
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        
        bandera++;
        if(bandera != MetodoSimplexRevisado.salidaFinal.size()){
            btnContinuar.setEnabled(true);
            datosSalida.setText(MetodoSimplexRevisado.salidaFinal.get(bandera));
            
        }
        if(bandera == MetodoSimplexRevisado.salidaFinal.size()-1){
            btnContinuar.setEnabled(false);
        }
    }//GEN-LAST:event_btnContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JTextArea datosSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
